@url = https://cautious-chainsaw-9rvjpqww7xg376pv-3000.app.github.dev/api/tarefas

GET {{url}}

###
POST {{url}}
Content-type: application/json

{
    "id": 10,
    "title": "Executar Aplicação"
}

###
GET {{url}}/2